export const ADD_NEW_TRANSACTION = 'ADD_NEW_TRANSACTION';
export const BULK_ADD_TRANSACTIONS = 'BULK_ADD_TRANSACTIONS';
export const BULK_DELETE_TRANSACTIONS = 'BULK_DELETE_TRANSACTIONS';
export const UPDATE_TRANSACTION = 'UPDATE_TRANSACTION';
export const DELETE_TRANSACTION = 'DELETE_TRANSACTION';
export const CLEAR_TRANSACTIONS = 'CLEAR_TRANSACTIONS';
export const DRAG_TRANSACTION = 'DRAG_TRANSACTION';
export const UPDATE_TRANSACTIONS_FILTERS = 'UPDATE_TRANSACTIONS_FILTERS';
export const SELECT_TRANSACTION = 'SELECT_TRANSACTION';
export const UNSELECT_TRANSACTION = 'UNSELECT_TRANSACTION';
export const SELECT_ALL_TRANSACTIONS = 'SELECT_ALL_TRANSACTIONS';
export const UNSELECT_ALL_TRANSACTIONS = 'UNSELECT_ALL_TRANSACTIONS';

export const UPDATE_FORECAST = 'UPDATE_FORECAST';

export const SET_ACTIVE_TAB = 'SET_ACTIVE_TAB';

export const UPDATE_GLOBAL_FILTER = 'UPDATE_GLOBAL_FILTER';

export const CREATE_TAG = 'CREATE_TAG';
export const DELETE_TAG = 'DELETE_TAG';
export const UPDATE_TAG = 'UPDATE_TAG';
export const CLEAR_TAGS = 'CLEAR_TAGS';

export const UPDATE_TAGS_VIEW = 'UPDATE_TAGS_VIEW';
