export const UPDATE_LIST_OF_PRODUCTS_FILTER = 'UPDATE_LIST_OF_PRODUCTS_FILTER',
	CLEAR_LIST_OF_PRODUCTS_FILTERS = 'CLEAR_LIST_OF_PRODUCTS_FILTERS',
	GET_PRODUCTS_REQUEST_SUCCESS = 'GET_PRODUCTS_REQUEST_SUCCESS',
	GET_PRODUCTS_REQUEST_PENDING = 'GET_PRODUCTS_REQUEST_PENDING',
	GET_PRODUCTS_REQUEST_ERROR = 'GET_PRODUCTS_REQUEST_ERROR',
	SET_SETTINGS_PRODUCTS_CATEGORIES = 'SET_SETTINGS_PRODUCTS_CATEGORIES',
	SET_SETTINGS_SIZE = 'SET_SETTINGS_SIZE',
	SET_FILTERS_SETTINGS = 'SET_FILTERS_SETTINGS';

