export const INCREMENT_PRODUCT_NUMBER_OF_ITEMS = 'INCREMENT_PRODUCT_NUMBER_OF_ITEMS',
	DECREMENT_PRODUCT_NUMBER_OF_ITEMS = 'DECREMENT_PRODUCT_NUMBER_OF_ITEMS',
	UPDATE_PRODUCT_NUMBER_OF_ITEMS = 'UPDATE_PRODUCT_NUMBER_OF_ITEMS';
