export const ADD_NEW_TRANSACTION = 'ADD_NEW_TRANSACTION';
export const BULK_ADD_TRANSACTIONS = 'BULK_ADD_TRANSACTIONS';
export const UPDATE_TRANSACTION = 'UPDATE_TRANSACTION';
export const DELETE_TRANSACTION = 'DELETE_TRANSACTION';
export const CLEAR_TRANSACTIONS = 'CLEAR_TRANSACTIONS';
export const DRAG_TRANSACTION = 'DRAG_TRANSACTION';

export const CREATE_TAG = 'CREATE_TAG';
