export const ADD_NEW_TRANSACTION = 'ADD_NEW_TRANSACTION';
export const BULK_ADD_TRANSACTIONS = 'BULK_ADD_TRANSACTIONS';
export const UPDATE_TRANSACTION = 'UPDATE_TRANSACTION';
export const DELETE_TRANSACTION = 'DELETE_TRANSACTION';
export const CLEAR_TRANSACTIONS = 'CLEAR_TRANSACTIONS';
export const DRAG_TRANSACTION = 'DRAG_TRANSACTION';
export const UPDATE_TRANSACTIONS_FILTERS = 'UPDATE_TRANSACTIONS_FILTERS';
export const CHANGE_VISIBILITY_BY_FILTER = 'CHANGE_VISIBILITY_BY_FILTER';

export const CREATE_TAG = 'CREATE_TAG';

export const UPDATE_FORECAST = 'UPDATE_FORECAST';
